[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "alembic>=1.16.3,<2.0.0",
    "bcrypt>=3.2.0,<4.0.0",
    "fastapi>=0.116.0,<1.0.0",
    "openai>=1.99.9,<2.0.0",
    "openai-agents>=0.2.8,<0.3.0",
    "passlib[argon2,bcrypt]>=1.7.4,<2.0.0",
    "psycopg>=3.2.9,<4.0.0",
    "psycopg-binary>=3.2.9,<4.0.0",
    "pydantic>=2.11.7,<3.0.0",
    "python-dotenv>=1.1.1,<2.0.0",
    "python-jose[cryptography]>=3.5.0,<4.0.0",
    "python-multipart>=0.0.20,<1.0.0",
    "sqlalchemy>=2.0.41,<3.0.0",
    "uvicorn[standard]>=0.35.0,<1.0.0",
    "websockets>=15.0.1,<16.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1,<9.0.0",
    "pytest-asyncio>=1.0.0,<2.0.0",
    "ruff>=0.12.2,<1.0.0",
]

[tool.uv]
add-bounds="major"

# ruffの設定
# defaultの設定は以下を参照
# https://docs.astral.sh/ruff/configuration/

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py313"
# alembic/versions配下はruffの対象外にする
exclude = [
    "alembic/versions/*",
]

[tool.ruff.lint]
# チェック・修正するルール
# ルールの詳細は以下を参照
# https://docs.astral.sh/ruff/rules/
select = [
    "F",    # Pyflakes
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "C90",  # mccabe
    "I",    # isort (ruff check --fixでisortに相当するformatが実行される)
    "N",    # pep8-naming
    "B",    # flake8-bugbear
    "S",    # flake8-bandit
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
]
# 除外するエラー
ignore = [
    "E501", # line-too-long: フォーマッタで調整できない場合は無視する(settingsやURLなど)
    "S101", # assert; テストで使うので無視する
    "B008", # TODO FastAPIの書き方と衝突しているので除外しなくてもいい様にする必要あり
]
# 修正しないエラー
unfixable = [
    "F401", # unused import
    "F841", # unused variable
]

[tool.ruff.format]
# フォーマッターの設定はdefaultを使用
