"""Add ToolExecution table and detailed tracking (Phase 2)

Revision ID: e268c0e18330
Revises: f6af6451a6d1
Create Date: 2025-07-24 14:01:46.799659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e268c0e18330'
down_revision = 'f6af6451a6d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('tool_call_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_arguments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('call_status', sa.String(), nullable=False),
    sa.Column('execution_status', sa.String(), nullable=True),
    sa.Column('tool_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('agent_reasoning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('has_detailed_executions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'has_detailed_executions')
    op.drop_table('tool_executions')
    # ### end Alembic commands ###