"""Simplify message table and remove tool_execution

Revision ID: f5042c074f67
Revises: e268c0e18330
Create Date: 2025-08-02 08:48:15.405173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5042c074f67'
down_revision = 'e268c0e18330'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_executions')
    op.drop_column('messages', 'tool_metadata')
    op.drop_column('messages', 'has_detailed_executions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('has_detailed_executions', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('tool_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('tool_executions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('execution_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tool_call_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tool_arguments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('call_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('execution_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tool_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('called_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('agent_reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('tool_executions_message_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tool_executions_pkey'))
    )
    # ### end Alembic commands ###