"""Add tool_metadata column to messages table

Revision ID: f6af6451a6d1
Revises: ef9a841e5b1a
Create Date: 2025-07-24 13:35:46.859269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6af6451a6d1'
down_revision = 'ef9a841e5b1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_metadata')
    # ### end Alembic commands ###